version: "2"

services:

  antora:
    image: ghcr.io/asam-ev/project-guide-docker:4
    volumes:
      - .:/usr/src/repo #has to match WORKSPACE defined in Dockerfile + folder from package.json "docker-build"
    depends_on:
      - kroki
      - blockdiag
      - mermaid
    ## Run interactively
    # entrypoint: /bin/bash
    
    ## Run with PDF generator. 
    ## BE AWARE that this currently does not support the use of (C) or (R)! You must alter the respective lines in osi-documentation/.antora/antora.yml. Make sure not to check these changes in!
    # entrypoint: antora --stacktrace --clean --extension @antora/pdf-extension site_local.yml # This creates a pdf on top of the html output. BE AWARE that this currently does not support the use of (C) or (R)! You must alter the respective lines in osi-documentation/.antora/antora.yml. Make sure not to check these changes in!

    ## Default generator setup
    entrypoint: antora --stacktrace --clean site_local.yml


  kroki:
    image: yuzutech/kroki:0.15.1
    environment:
      - KROKI_MAX_URI_LENGTH=20000
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid

  blockdiag:
    image: yuzutech/kroki-blockdiag:0.15.1

  mermaid:
    image: yuzutech/kroki-mermaid:0.15.1
