site:
  title: ASAM OSI (Open Simulation Interface)
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://opensimulationinterface.github.io/osi-documentation/
  start_page: asamosi::index.adoc # Replace "latest" with the last released version, e.g. 1.0.0

urls: # Activate this once the first release version goes live!!!
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest
  redirect_facility: nginx

content:
  edit_url: ~
  sources:
    - url: https://github.com/OpenSimulationInterface/osi-documentation.git # retrieve content from remote
    # - url: ./osi-documentation # retrieve content locally
      branches: [antora/base-antora-setup] # change to main later
      # branches: HEAD # build current HEAD
      tags: [v*,"!v1*", "!v3.5.0"]
      start_path: .antora
    - url: https://github.com/OpenSimulationInterface/open-simulation-interface.git # retrieve content from remote
    # - url: ./open-simulation-interface# retrieve content locally
      branches: [antora/base-antora-setup] # change to main later
      # branches: HEAD # build current HEAD
      tags: [v*,"!v2*", "!v3.0*", "!v3.1*", "!v3.2*", "!v3.3*", "!v3.4*", "!v3.5.0"]
      start_path: .antora
    - url: https://github.com/OpenSimulationInterface/osi-sensor-model-packaging.git # retrieve content from remote
    # - url: ./osi-sensor-model-packaging # retrieve content locally
      branches: [antora/base-antora-setup] # change to main later
      # branches: HEAD # build current HEAD
      tags: [v*,"!v0*", "!v1.0*", "!v1.1*", "!v1.2*", "!v1.3.0"]
      start_path: .antora
    - url: https://code.asam.net/common/style-resources.git
      branches: master      
      start_path: antora

ui:
  bundle:
    url: https://code.asam.net/common/style-resources/-/raw/master/antora/ui-bundle.zip?inline=false
    snapshot: true
  supplemental_files: ./supplemental_ui


output:
  clean: true
  dir: ./site

runtime:
  fetch: true

# tag::asciidoctor[]
asciidoc:
  attributes:
    page-pagination: true
    # page-width-limit: none@
    hide-uri-scheme:
    kroki-server-url: 'http://kroki:8000'
    kroki-fetch-diagram: ""
    # Allow URI read to retrieve SVG on compilation
    allow-uri-read: true
    # use SVG unless otherwise specified
    kroki-default-format: svg
    # Make SVG inline so that we can get interactive actions (can be overridden by schema with "opts=none")
    kroki-default-options: interactive
    # Configuration for feedback button. The button is defined in the header-content.hbs in ./supplemental_ui/partials
    page-feedbackurl: 'https://github.com/OpenSimulationInterface/open-simulation-interface/issues/new@'
    page-feedbacktype: github
    sectnums: "@"
    xrefstyle: short@
    toclevels: 3
    asciidoc-resources: ASAM_Syle_Resources:ROOT:partial$asciidoc-resources

    ## Labels
    mandatory: '<label class="mandatory"/>'
    recommended: '<label class="recommended"/>'
    optional: '<label class="optional"/>'

  extensions:
  - asciidoctor-kroki
  # - '@djencks/asciidoctor-mathjax'
  - './asam-antora-extensions/asam-asciidoctor_extensions-registered.js'
  - './asam-antora-extensions/asam-asciidoctor_extensions.js'
# end::asciidoctor[]


# tag::antora[]
antora:
  extensions:
    - require: '@antora/lunr-extension'
    - require: './asam-antora-extensions/asam-antora_extension.js'
      numbered_titles: true
      section_number_style: 'iso'
      alternate_xref_style: 'full'
      loft: true
      local_to_global_references: true
      doxygen: true

  # end::antora[]