name: ASAM OSI build

on:
  # create: # new branches or tags
  # release: # new releases
  # pull_request:
  push: # on push
    branches:
    - main
  schedule: # periodic - needed because some of the content is from the other repos
    - cron:  '30 5,20 * * *' # twice per day, in the morning and evening.

jobs:
  build:
    name: Build OSI documentation and deploy it to gh-pages
    runs-on: ubuntu-20.04

    services:
      kroki:
        image: yuzutech/kroki:0.15.1
        env:
          KROKI_MAX_URI_LENGTH: 8000
          KROKI_BLOCKDIAG_HOST: blockdiag
          KROKI_MERMAID_HOST: mermaid
      blockdiag:
        image: yuzutech/kroki-blockdiag:0.15.1
      mermaid:
        image: yuzutech/kroki-mermaid:0.15.1


    steps:

    # checkout repo into folder guide. This is done to match the setup for the local build in docker-compose
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: repo
        fetch-depth: 0 # test if depth in fetch history is required
        
    - name: Submodules
      working-directory: repo
      env: 
        ASAM_ANTORA_EXTENSIONS: ${{ secrets.ASAM_ANTORA_EXTENSIONS }}
      run: git clone https://asam-antora-extensions:$ASAM_ANTORA_EXTENSIONS@code.asam.net/common/asam-antora-extensions.git
        

    # build site
    - name: Generate site
      uses: docker://ghcr.io/asam-ev/project-guide-docker:4
      with:
        entrypoint: sh
        args: repo/run-build.sh
    
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v1
      with: 
        path: ./repo/site

  deploy:
    # Allow one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true

    needs: build
    permissions: 
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v1
